//AUTH SUCCESS DATA
export const SET_AUTH_DATA_SUCCESS = 'SET_AUTH_DATA_SUCCESS'

//EMPLOYEES
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
export const ADD_EDIT_EMPLOYEE = 'ADD_EDIT_EMPLOYEE'
export const RESET_EDIT_EMPLOYEE = 'RESET_EDIT_EMPLOYEE'
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'

//STATISTICS
export const SET_STATISTIC = 'SET_STATISTIC'
export const SET_SAMPLE_STATISTIC = 'SET_SAMPLE_STATISTIC'
